POST http://localhost:5016/api/employee
Content-Type: application/json

{
  "firstName": "Admin",
  "lastName": "User",
  "email": "admin@company.com",
  "passwordHash": "Elpasso-00112",
  "title": "Administrator",
  "role": 2
}